### ISSUE TITLE
No known class method for selector 'sha265:'

### ISSUE THREAD

**Issue by janpieterz** [FormidableLabs/react-native-app-auth#256]
## Issue

Builds fail after upgrading to version 4.1.0. Seems to be a typo (265 instead of 256)?
https://github.com/FormidableLabs/react-native-app-auth/blob/f45173b95f45162e0f0297a40e7b50df07295e3c/ios/RNAppAuth.m#L162

---

## Environment

- **Your Identity Provider**: `e.g. IdentityServer 4 / Okta / Azure`
Not relevant
- **Platform that you're experiencing the issue on**:
  - [x] iOS
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No

**Comment by kadikraman** [comment]
Could you tell me what version of AppAuth-iOS you're using?

I merged a PR that added this and then reverted the change that converted 265 -> 256 in [this PR](https://github.com/FormidableLabs/react-native-app-auth/pull/231) since it's a [naming change](https://github.com/openid/AppAuth-iOS/commit/87b0823ced25ecfbed07a36adddd508281bfe546) that AppAuth-iOS fixed in `AppAuth-iOS/1.0.0.beta1` & I didn't want to depend on it until they've properly released a v1.

**Comment by janpieterz** [comment]
That’s it, using the beta version. Will revert to latest non-beta.

**Comment by janpieterz** [comment]
Sorted, builds are green again. Thanks kadiraman, apologies for jumping on this!

**Comment by hadnazzar** [comment]
I am still having that issue. 

![Screenshot 2019-03-22 at 14 51 32](https://user-images.githubusercontent.com/20724096/54827334-01d2e980-4cb2-11e9-82ba-4b9a9fc71cff.png)

**Comment by janpieterz** [comment]
@hadnazzar Odd, can you copy the podfile here?

**Comment by hadnazzar** [comment]
@janpieterz 

I am using the latest master 

`github "openid/AppAuth-iOS" "master"`

**Comment by janpieterz** [comment]
@hadnazzar The latest master isn't compatible with the `react-native-app-auth` library.
I'd recommend using `pod 'AppAuth', '0.95.0'` to ensure you're using the correct version.

**Comment by hadnazzar** [comment]
@janpieterz can you share your pod file with please?

**Comment by janpieterz** [comment]
Sure:

```
platform :ios, '9.0'

target 'SampleApp' do
  pod 'AppAuth', '0.95.0'
end
```

**Comment by hadnazzar** [comment]
@janpieterz thank you so much i tried with 0.95.0 too. 

It is working right now 👍

**Comment by perry-mitchell** [comment]
@janpieterz Hello! I'm still getting this error - with a fresh install of the library at `4.4.0`. Pod installed as per instructions here. Rather than opening a new issue I was hoping you might be able to point be in the right direction here.

![image](https://user-images.githubusercontent.com/3869469/61637553-6d4cb800-aca0-11e9-9ebb-0ddede856747.png)

My Podfile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BCAutoFillExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BCAutoFillExtension

end

target 'Buttercup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buttercup
  pod 'AppAuth', '>= 0.94'

  target 'ButtercupTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Buttercup-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buttercup-tvOS

  target 'Buttercup-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by perry-mitchell** [comment]
In fact, if I check the latest stable tag, the bug is still present there:

https://github.com/FormidableLabs/react-native-app-auth/blob/v4.4.0/ios/RNAppAuth.m#L162-L163

**Comment by janpieterz** [comment]
@perry-mitchell Are you sure your pod is resolved to 0.94 and not to a later version?

**Comment by perry-mitchell** [comment]
@janpieterz The `Podfile.lock` is as follows:

```
PODS:
  - AppAuth (1.0.0):
    - AppAuth/Core (= 1.0.0)
    - AppAuth/ExternalUserAgent (= 1.0.0)
  - AppAuth/Core (1.0.0)
  - AppAuth/ExternalUserAgent (1.0.0)

DEPENDENCIES:
  - AppAuth (>= 0.95)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - AppAuth

SPEC CHECKSUMS:
  AppAuth: c42547576838bf025b852736dd9b8a1c943fe68f

PODFILE CHECKSUM: 83d4a7247cfb35db0df977839fc72910bf5e706c

COCOAPODS: 1.7.5
```

But I don't understand.. The latest stable version seems to still have that typo. I see no newer version (besides master and the beta) that has that changed.

Thanks for the help!

**Comment by janpieterz** [comment]
Hi @perry-mitchell , you'll have to depend either on the latest beta (`v5.0.0-rc1`) or revert AppAuth to use v 0.94 or 0.95 specifically. See above for the podfile used.

**Comment by perry-mitchell** [comment]
@janpieterz That was it entirely, thanks for spelling it out for me. Cheers!

**Comment by kadikraman** [comment]
Thanks for being the MVP here @janpieterz 🙌

**Comment by BatchOfCookies12** [comment]
Sorry to add chatter, but did anyone else notice the issue number here is 256? It seems coincidental considering the issue its that 265 needs to instead be 256 😆 .
