### ISSUE TITLE
Redirection issue with Azure two step authentication

### ISSUE THREAD

**Issue by shamprasadrh** [FormidableLabs/react-native-app-auth#486]
## Issue

Azure AD login does not work successfully when two step authentication is enabled. After inputing the user name password it asks for OTP/Authenticator approval. Post OTP app doesn't redirect properly to app instead we get an error message. This happens only when users are logging from outside company network using two-factor authentication. Normal single step authentication works perfectly with out issue. 

<img width="414" alt="IMG_1677B5B7D011-1" src="https://user-images.githubusercontent.com/28918386/77296020-e8251180-6d0c-11ea-9be6-b87c2bb2d3bc.png">

---

## Environment

* **Your Identity Provider**: ` Azure`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?**: `no`

**Comment by shamprasadrh** [comment]
Hi Anyone has faced the same issue? after some research looks like an issue with the Safari.

**Comment by kadikraman** [comment]
Which version of this library are you using? I recall this issue being fixed with https://github.com/FormidableLabs/react-native-app-auth/pull/415 in v5

**Comment by TheMatrixMaster** [comment]
### Description
This issue still persists on iOS14. We are using the latest react-native-app-auth version (v6.2.0). Following a standard Azure Active Directory v2 authentication request, the user leaves our app to validate two-factor authentication in Microsoft Authenticator app. This will resolve the request and return the appropriate access tokens which we then want to send to our server. However, the network request that gets created when the app is in the background gets killed immediately instead of staying intact until the user re-accesses the app.

### Verification
This video link shows the described behaviour above.
https://drive.google.com/file/d/1LMs6t76iSaTyu4vdR5Gk5ZqaKsjwJCEe/view?usp=sharing
